### PR TITLE
Link to source repository

### PR DESCRIPTION
**Pull request by BigBlueHat**
Because I'm tired of searching GitHub for it. :wink:

### CODE REVIEW

**Comment by dlongley** [comment]
Heh, we're going to nuke that home page soon. This branch will likely be merging into master very soon along with a new home page:

https://github.com/digitalbazaar/authorization.io/tree/credential-handler

There's also a new demo here:

https://credential-repository.demo.digitalbazaar.com

That we will link off of that new home page.

**Comment by BigBlueHat** [comment]
Oh! Great to know! Also, this demo is much clearer. Thanks. 😄

**Comment by BigBlueHat** [comment]
Except...there's still no link to this repo. 😉 Might want to fix that...or await a future PR from me. 😁

**Comment by dlongley** [comment]
We'll have a link here on authorization.io for the auth.io code, but we should probably put a link to the demo code on the demo site. The demo *uses* auth.io as a "credential mediator". We'll have some better docs on what that means (the architecture for the Credential Handler API) at some point.

**Pull request closed without merging**
